### ISSUE TITLE
Les 3 (gitintro) de eerste rendert niet naar html

### ISSUE THREAD

**Issue by amdehaan** [DataScienceILC/tlsc-dsfb26v-20_workflows#47]
.md wordt wel gemaakt, html niet. Als je dezelfde .Rmd er twee keer in zit, pakt hij wel de tweede, dus iets met te vroeg aanroepen van iets wat nog niet bestaat?

Ligt niet aan methode zonder _main, dat heb ik al geprobeerd.
Ligt niet aan stukjes bash

Soort van gefixed for now, eerst de inhoud af voor ik er weer naar wil kijken. Als iemand weet wat bookdown tegen heeft op les 3: graag :)

**Comment by Maddocent** [comment]
Bij mij doet ie t lokaal wel. Zit toch in de reader al?

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________
From: amdehaan ***@***.***>
Sent: Saturday, April 3, 2021 5:49:26 PM
To: DataScienceILC/tlsc-dsfb26v-20_workflows ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DataScienceILC/tlsc-dsfb26v-20_workflows] Les 3 (gitintro) de eerste rendert niet naar html (#47)


.md wordt wel gemaakt, html niet. Als je dezelfde .Rmd er twee keer in zit, pakt hij wel de tweede, dus iets met te vroeg aanroepen van iets wat nog niet bestaat?

Ligt niet aan methode zonder _main, dat heb ik al geprobeerd.
Ligt niet aan stukjes bash

Soort van gefixed for now, eerst de inhoud af voor ik er weer naar wil kijken. Als iemand weet wat bookdown tegen heeft op les 3: graag :)
