### ISSUE TITLE
sometimes the css tag "dagopdracht" does automated numbering, sometimes not...

### ISSUE THREAD

**Issue by Maddocent** [DataScienceILC/tlsc-dsfb26v-20_workflows#58]
add markup example to css style sheet examples

**Comment by amdehaan** [comment]
De teller hangt niet aan "dagopdracht", maar aan H5
Dus als je er ##### voor zet autonummert hij, anders niet. Ik kan eventueel ook een teller in de css laten lopen voor de dagopdrachten, maar dat zijn er niet zoveel.
