### ISSUE TITLE
 example of a readme file image is barely readable, 2.6 metadata

### ISSUE THREAD

**Issue by Larsdegroot** [DataScienceILC/tlsc-dsfb26v-20_workflows#74]
A image that displays an example of a README.txt file is barely readable. My guess is that this image was made using `print screen` and then cropped? maybe using the windows snipping tool with the .txt as an maximized window will yield better results

**Comment by amdehaan** [comment]
geprobeerd:
- dpi en fig.widt helpen niet for some reason. Heb jij een nieuwe screenshot, Marc?

**Comment by Maddocent** [comment]
I believe this is stale and fixed
